### ISSUE TITLE
Scraping dont work

### ISSUE THREAD

**Issue by TheCherry** [bite-your-idols/Gamestarter#107]
Scraping for both Emulatorstation and ASL don't work. They can't find any game from the Websites.
Seems to be a problem that got fixed for around 4 months, maybe we need new bins?

https://retropie.org.uk/forum/topic/18435/emulationstation-scraper-not-working/65

**Comment by bite-your-idols** [comment]
If AEL don't scrape and you are following the steps provided by developer yiu should ask him for help in kodi forum AEL's thread, he will helo you for sure.

About ES, scrapping somedays sucks because it uses gamesdb database and the site is offline more than online... Also ES binaries are grabbed from a deprecated LibreELEC custom rom that is no longer updated.
