### ISSUE TITLE
EmulationStation Version

### ISSUE THREAD

**Issue by Drarkklain** [bite-your-idols/Gamestarter#109]
I would like to know if you could update the version of emulationstation to 2.8 (it's the same used on retropie), that version support more themes,  can you?

**Comment by bite-your-idols** [comment]
ES binaries are grabbed from a deprecated LibreELEC custom build that is no longer updated. Retropie's version does not work because it is compiled to run under raspbian, not under libreelec so the only way to update it (if newer retropie's branch is compatible with non Retropie projects) is when someone compiles it for LibreElec's toolchain... so maybe never...
