### ISSUE TITLE
Missing libXi.so.6

### ISSUE THREAD

**Issue by ramon-kramer** [bite-your-idols/Gamestarter#110]
Hi, i need the libXi.so.6 library for Generic x64 Build to use Dolphin Core in Retroarch. It is not found in the Package Repos (Only for RPi). Any Ideas?

Regards

**Comment by bite-your-idols** [comment]
you can install this custom build https://forum.libreelec.tv/thread/12662-libreelec-9-0-reborn-remix-emulationstation-retroarch-dolphinqt-moonlight-chrome/?pageNo=1 and copy wanted libs from there, I guess it should include all needed ones since it is a very complete and advenced build focused in emulation.
