### ISSUE TITLE
[Feature-Request] Automatic synchronization of the saves to a server

### ISSUE THREAD

**Issue by update-freak** [bite-your-idols/Gamestarter#148]
I have a suggestion for another feature (RetroArch in LibreELEC, RPi3):
It would be great if the saves (from GBA, SNES) could be automatically synchronized to a server, e.g. via WebDAV or FTP or SMB.
I am currently using SFTP (when RPi started in LibreELEC) to load the saves onto my PC via Filezilla and then copy them to the Synology NAS. A bit awkward, I think. It would be nice if there is something in the future that would make this process easier.

**Comment by bite-your-idols** [comment]
Maybe you can take a look to any "cloud" addon and set your saves folder to that one. I have a Google drive addon and I can set in retroach my save folder to a folder in my gdrive so it uploads it automatically. It is not an easy feature to include in RA addon since you need accounts, logins, sync... The easiest way is that libretro team release any kind of cloud save.

**Comment by update-freak** [comment]
ok, thanks. I'm going to look for addons to sync for LibreELEC
