### ISSUE TITLE
Emulator sounds work via advanced launcher, but not via emulation station

### ISSUE THREAD

**Issue by dberg81** [bite-your-idols/gamestarter#5]
I installed the gamestater via SSH on a RPI 3 running Openelec 6.95.3 and I'm noticing some odd behavior with sound between roms launched in advanced launcher and emulationstation/retroarch.  I originally configured my roms to launch via advanced launcher, but I quickly discovered it was not ideal getting brought straight back to the Kodi home screen after exiting a ROM.  I wanted the emulator to exit back to a rom browser GUI, so gamestater: emulationstation proved to be a better fit for me.  

Unfortunately I cannot get sound working through any roms launched in the gamestater: emulationstation add-on, nor do I get any sound if I open a rom directly in the gamestarter: retroarch add-on.  It's important to note I'm trying to get the sound to output via HDMI and not the 3.5mm jack. The only time sound is working with roms is when I launch them via advanced launcher.  I've tried numerous troubleshooting tips for retroarch and raspberry pi audio issues, but unfortunately I've had no success getting audio to work in gamestarter: emulationstation.  Here's an idea of what I'm talking about:
https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=103773  

Any help you can provide would be much appreciated.

**Comment by bite-your-idols** [comment]
It is an strange issue because the three methods use the same config file for retroarch emulators...
Please launch a rom with advanced launcher and when running with sound type via ssh "aplay -l", then launch the same rom using retroarch launcher addon and do the same. Finally repeat the process with emulationstation launcher addon. The check if the three results of "aplay -l" command are the same. In openelec 7beta I also had some strange random sound issues related. 
What I recommend to you is to make a backup and then update to LibreELEC 7, it solved all my issues... maybe it does for you...

Also, you can test this: Launch a rom with advanced launcher, then enter retroarch menu and select another rom, does it sound?

**Comment by dberg81** [comment]
Thanks for the response.  Running "aplay -l" and "aplay -L" returned the same audio data while running roms under advanced launcher, retroarch and emualtionstation.  Instead of spending any additional time troubleshooting audio in openelec 7 beta, I took your suggestion and upgraded to libreelec 7.  I ended up formatting my microSD and going with a fresh build.  

After booting into KODI and reinstalling gamelauncher, I'm happy to report that audio is now working for all roms across all emulator platforms.  Looks like the libreelec upgrade did the trick.

Thanks so much for your help!
