### ISSUE TITLE
File gamestarter.sh not found

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter#72]
After using Adv. Launcher (2.5.8).

RPi2, LE 8.0.2, RetroArch 1.0

**Comment by bite-your-idols** [comment]
This is because you are using AEL categories.xml from Gamestarer addon and now you are using retroarch addon. You have some alternatives:
- If you have a lot of customization (like a lot of roms scraped) in AEL you can edit categories.xml and search/replace "/storage/.kodi/addons/script.gamestarter/resources/bin/gamestarter.sh" with "/storage/.kodi/addons/game.retroarch/addon.sh"

- Easiest way is just to reinstall AEL from gamestarter repo then move categories.xml file from /storage/.kodi/addons/plugin.program.advanced.emulator.launcher/ to /storage/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/

**Comment by drrak** [comment]
* Kodi reboot
* Kodi reboot

**Comment by bite-your-idols** [comment]
Did you download atari2600 libretro core? You can do it from addon settings or from retroarch gui settings. Retroarch addon can aldo detect retroplayer (LE 9 testbuild) downloaded cores.

**Comment by drrak** [comment]
Now it is ok.

Thank you.
