### ISSUE TITLE
Dreamcast Raspberry 

### ISSUE THREAD

**Issue by pablinho1023** [bite-your-idols/Gamestarter#78]
Hi! Thank you so much for the addon, i have been using it for a while with openelec on a rpi 3, the thing is that i cant seem to make dreamcast games work, im using it with iarl, selecting external launch and using reicast but when the game downloads the screen goes Black and take me to the openelec menú again, i tried to launch the game in retroarch directly but i cant find any core for dreamcast,  what should i do?

**Comment by bite-your-idols** [comment]
There is no Dreamcast working core for Raspberries. If you use Generic x64_68 you can use reicast core but in Raspberry this is a very slow and full of bugs core. Raspberry isn't power enough to emualte this console, even using native Reicast emulator instead of libretro core is very slow and buggy as you can read in retropie's documetation:
https://github.com/RetroPie/RetroPie-Setup/wiki/Dreamcast
