### ISSUE TITLE
Emulation Station launch Error

### ISSUE THREAD

**Issue by symbios24** [bite-your-idols/Gamestarter#97]
Hi, upon launching of EmulatioStation from gamestarter on latest LibreElec version on a Rpi3 i get this message from emulation station "we cant find any systems check  that your paths are correct in the systems configuration file and your game directory has at least one game with the correct extension" the only option i have is quit
I did everything described in your info downloaded cores,put games in the directory etc
i always get this message

Thanks

**Comment by bite-your-idols** [comment]
take a look to /storage/.kodi/userdata/addon_data/game.emulationstation/es_systems.cfg to check what paths and extensions do you have for each system and make sure you have at least one file (with the correct extension) of one of the systems in the correct folder.

If you didn't modify path, default one is "/storage/emulators/roms/system_name".

Also, you can try to edit es_systems.cfg file using addon settings and there you can modify path and default core/emulator for each system.

One question, if you launch retroarch you can play a rom?

**Comment by symbios24** [comment]
i tried retro-arch loaded the rom but nothing the screen was black

**Comment by symbios24** [comment]
i loaded only one core from retroarch snes2010
how can i edit this locations does libreelec has command line?
or i have to put the card to another linux machine?

**Comment by bite-your-idols** [comment]
ok, that seems to be another issue, one thing at a time. First try what I said about es_systems.cfg file and paths.

**Comment by bite-your-idols** [comment]
You can change roms path editing that value in ES addon settings. Then generate es_systems.cfg again.
Also for cores, as you said you can edit assigned core name for each system in addon settings. Those names must be the same as the cores you dowload both using Retroarch addon settings (download full lakka package) or using retroarch in-app settings "download core" option.
ES can not be updated since it is a abandoned project, just retropie and recalbox forks are updated but they can not be used outside its project.
About libretro cores you can download latest official lakka release package, when lakka releases a new version I will update that package, in the meanwhile you can use retroarch's in-app "download core" option that will download it from latest [retroarch buildbot](http://buildbot.libretro.com/nightly/linux/armhf/latest/), some of them may not work in RPi.

**Comment by symbios24** [comment]
hi again, is the USB ROM Transfer Service working with emulation station?

thanks

**Comment by bite-your-idols** [comment]
I don't know what you mean, but if you connect a USB drive to your RPi and Libreelec/kodi detects it you can use that path for emulationstation an retroarch.

**Comment by symbios24** [comment]
i mean this:


first create a folder called retropie on your USB stick
plug it into the pi and wait for it to finish blinking
pull the USB out and plug it into a computer
add the roms to their respective folders (in the retropie/roms folder)
plug it back into the raspberry pi
wait for it to finish blinking
you can now remove the USB stick.
refresh emulationstation by pressing F4, or choosing quit from the start menu

**Comment by bite-your-idols** [comment]
I see. Retropie has that feature because it doesnt allow to run games from USB drives out the box, so it includes that workaround. In Libreelec it is not needed since you can store your games where you want and then point emulationstation and/or retroarch to that location.
Also you can use kodis file explorer to copy or move roms as you want.

**Comment by symbios24** [comment]
ok thanks
